In [4]:
import pandas as pd
import numpy as np

In [5]:
one=pd.read_excel('教学信息.xlsx')
one

      学号   姓名 性别  年龄  身高 (cm)  体重 (kg)   籍贯  考试成绩
0      1   邓娟  女  21      184       56  陕西省     7
1      2   王畅  男  25      155       72  青海省    30
2      3   储岩  女  23      166       56  辽宁省    28
3      4   徐莉  女  24      150       57  山西省    98
4      5   李波  男  20      175       55  海南省    14
..   ...  ... ..  ..      ...      ...  ...   ...
495  496  陈金凤  女  20      172       57  河北省    92
496  497   马洋  男  19      173       56  上海市    48
497  498   李峰  女  24      151       71  台湾省    98
498  499   王勇  女  25      154       69  上海市    38
499  500  王建平  男  18      157       47  陕西省    77

[500 rows x 8 columns]

In [6]:
student=pd.read_excel('教学信息.xlsx',sheet_name='学生')
student.iloc[:5]

   学号  姓名 性别  年龄  身高 (cm)  体重 (kg)   籍贯  考试成绩
0   1  邓娟  女  21      184       56  陕西省     7
1   2  王畅  男  25      155       72  青海省    30
2   3  储岩  女  23      166       56  辽宁省    28
3   4  徐莉  女  24      150       57  山西省    98
4   5  李波  男  20      175       55  海南省    14

In [16]:
student.iloc[-10:]

      学号   姓名 性别  年龄  身高 (cm)  体重 (kg)       籍贯  考试成绩 身高_带单位 体重_带单位  身高 (m)
490  491  王桂香  女  25      183       83      福建省    87  183厘米   83千克    1.83
491  492   陈宁  男  23      171       52  宁夏回族自治区    81  171厘米   52千克    1.71
492  493  邓小红  女  21      190       57      河北省    25  190厘米   57千克    1.90
493  494   薛敏  男  20      179       45  广西壮族自治区    38  179厘米   45千克    1.79
494  495   涂飞  女  22      178       56  澳门特别行政区    28  178厘米   56千克    1.78
495  496  陈金凤  女  20      172       57      河北省    92  172厘米   57千克    1.72
496  497   马洋  男  19      173       56      上海市    48  173厘米   56千克    1.73
497  498   李峰  女  24      151       71      台湾省    98  151厘米   71千克    1.51
498  499   王勇  女  25      154       69      上海市    38  154厘米   69千克    1.54
499  500  王建平  男  18      157       47      陕西省    77  157厘米   47千克    1.57

In [17]:
student.loc[:, ['姓名', '性别']]

      姓名 性别
0     邓娟  女
1     王畅  男
2     储岩  女
3     徐莉  女
4     李波  男
..   ... ..
495  陈金凤  女
496   马洋  男
497   李峰  女
498   王勇  女
499  王建平  男

[500 rows x 2 columns]

In [44]:
student.iloc[20:51]
student.loc[student['身高 (cm)']>170]

,学号,姓名,性别,年龄,身高 (cm),体重 (kg),籍贯,考试成绩,身高_带单位,体重_带单位,身高 (m),5级成绩
0,1,邓娟,女,21,184,56,陕西省,7,184厘米,56千克,1.84,不及格
4,5,李波,男,20,175,55,海南省,14,175厘米,55千克,1.75,不及格
5,6,陈雷,男,23,178,59,云南省,8,178厘米,59千克,1.78,不及格
6,7,李兵,女,21,181,83,北京市,35,181厘米,83千克,1.81,不及格
8,9,蒙玉英,女,21,172,75,云南省,90,172厘米,75千克,1.72,优秀
...,...,...,...,...,...,...,...,...,...,...,...,...
492,493,邓小红,女,21,190,57,河北省,25,190厘米,57千克,1.90,不及格
493,494,薛敏,男,20,179,45,广西壮族自治区,38,179厘米,45千克,1.79,不及格
494,495,涂飞,女,22,178,56,澳门特别行政区,28,178厘米,56千克,1.78,不及格
495,496,陈金凤,女,20,172,57,河北省,92,172厘米,57千克,1.72,优秀
496,497,马洋,男,19,173,56,上海市,48,173厘米,56千克,1.73,不及格

In [19]:
student.loc[student['性别'] == '男']

      学号   姓名 性别  年龄  身高 (cm)  体重 (kg)        籍贯  考试成绩 身高_带单位 体重_带单位  身高 (m)
1      2   王畅  男  25      155       72       青海省    30  155厘米   72千克    1.55
4      5   李波  男  20      175       55       海南省    14  175厘米   55千克    1.75
5      6   陈雷  男  23      178       59       云南省     8  178厘米   59千克    1.78
7      8   林英  男  22      162       51       海南省     1  162厘米   51千克    1.62
9     10   李涛  男  24      164       78  新疆维吾尔自治区    84  164厘米   78千克    1.64
..   ...  ... ..  ..      ...      ...       ...   ...    ...    ...     ...
486  487   唐楠  男  24      157       55       海南省    56  157厘米   55千克    1.57
491  492   陈宁  男  23      171       52   宁夏回族自治区    81  171厘米   52千克    1.71
493  494   薛敏  男  20      179       45   广西壮族自治区    38  179厘米   45千克    1.79
496  497   马洋  男  19      173       56       上海市    48  173厘米   56千克    1.73
499  500  王建平  男  18      157       47       陕西省    77  157厘米   47千克    1.57

[263 rows x 11 columns]

In [20]:
student.loc[(student['年龄']>19)&(student['年龄']<22)]

      学号   姓名 性别  年龄  身高 (cm)  体重 (kg)        籍贯  考试成绩 身高_带单位 体重_带单位  身高 (m)
0      1   邓娟  女  21      184       56       陕西省     7  184厘米   56千克    1.84
4      5   李波  男  20      175       55       海南省    14  175厘米   55千克    1.75
6      7   李兵  女  21      181       83       北京市    35  181厘米   83千克    1.81
8      9  蒙玉英  女  21      172       75       云南省    90  172厘米   75千克    1.72
12    13  江秀珍  女  21      153       79       河北省    62  153厘米   79千克    1.53
..   ...  ... ..  ..      ...      ...       ...   ...    ...    ...     ...
485  486  周秀珍  男  20      161       63  新疆维吾尔自治区    88  161厘米   63千克    1.61
488  489   李想  女  20      154       63       安徽省    35  154厘米   63千克    1.54
492  493  邓小红  女  21      190       57       河北省    25  190厘米   57千克    1.90
493  494   薛敏  男  20      179       45   广西壮族自治区    38  179厘米   45千克    1.79
495  496  陈金凤  女  20      172       57       河北省    92  172厘米   57千克    1.72

[133 rows x 11 columns]

In [21]:
student.loc[student['体重 (kg)'] > 70,['学号','姓名','体重 (kg)']]

      学号   姓名  体重 (kg)
1      2   王畅       72
6      7   李兵       83
8      9  蒙玉英       75
9     10   李涛       78
10    11   崔浩       85
..   ...  ...      ...
479  480  柯冬梅       72
483  484   钟燕       80
487  488   阮欣       72
490  491  王桂香       83
497  498   李峰       71

[216 rows x 3 columns]

In [22]:
teacher=pd.read_excel('教学信息.xlsx',sheet_name='教师')
teacher

      工号   姓名 性别  年龄
0   T001  胡秀珍  男  29
1   T002   赵想  男  40
2   T003   吴洁  女  47
3   T004   何俊  男  52
4   T005  李红霞  女  30
5   T006  张淑华  女  28
6   T007   罗畅  男  32
7   T008   萧辉  男  48
8   T009   陶勇  女  55
9   T010  游志强  女  33
10  T011  黎凤英  女  40
11  T012   江宇  女  52
12  T013  祝秀华  女  35
13  T014  李玉兰  女  46
14  T015   徐荣  女  44
15  T016   王飞  男  53
16  T017  吴金凤  男  28
17  T018   梁琳  女  41
18  T019   丁瑜  男  39
19  T020   黄明  女  35
20  T021   余峰  女  43
21  T022  王冬梅  男  45
22  T023  董淑兰  男  51
23  T024   曹飞  女  47
24  T025  李冬梅  女  43
25  T026   吴亮  男  28
26  T027   徐宇  女  49
27  T028   何萍  男  40
28  T029   葛莹  女  53
29  T030  罗海燕  女  34

In [23]:
teacher.groupby('性别').agg(数量=('姓名', 'count'))

    数量
性别
女   18
男   12

In [24]:
teacher['性别_数字'] = teacher['性别'].map({'男': 1, '女': 0})
teacher

      工号   姓名 性别  年龄  性别_数字
0   T001  胡秀珍  男  29      1
1   T002   赵想  男  40      1
2   T003   吴洁  女  47      0
3   T004   何俊  男  52      1
4   T005  李红霞  女  30      0
5   T006  张淑华  女  28      0
6   T007   罗畅  男  32      1
7   T008   萧辉  男  48      1
8   T009   陶勇  女  55      0
9   T010  游志强  女  33      0
10  T011  黎凤英  女  40      0
11  T012   江宇  女  52      0
12  T013  祝秀华  女  35      0
13  T014  李玉兰  女  46      0
14  T015   徐荣  女  44      0
15  T016   王飞  男  53      1
16  T017  吴金凤  男  28      1
17  T018   梁琳  女  41      0
18  T019   丁瑜  男  39      1
19  T020   黄明  女  35      0
20  T021   余峰  女  43      0
21  T022  王冬梅  男  45      1
22  T023  董淑兰  男  51      1
23  T024   曹飞  女  47      0
24  T025  李冬梅  女  43      0
25  T026   吴亮  男  28      1
26  T027   徐宇  女  49      0
27  T028   何萍  男  40      1
28  T029   葛莹  女  53      0
29  T030  罗海燕  女  34      0

In [25]:
student

      学号   姓名 性别  年龄  身高 (cm)  体重 (kg)   籍贯  考试成绩 身高_带单位 体重_带单位  身高 (m)
0      1   邓娟  女  21      184       56  陕西省     7  184厘米   56千克    1.84
1      2   王畅  男  25      155       72  青海省    30  155厘米   72千克    1.55
2      3   储岩  女  23      166       56  辽宁省    28  166厘米   56千克    1.66
3      4   徐莉  女  24      150       57  山西省    98  150厘米   57千克    1.50
4      5   李波  男  20      175       55  海南省    14  175厘米   55千克    1.75
..   ...  ... ..  ..      ...      ...  ...   ...    ...    ...     ...
495  496  陈金凤  女  20      172       57  河北省    92  172厘米   57千克    1.72
496  497   马洋  男  19      173       56  上海市    48  173厘米   56千克    1.73
497  498   李峰  女  24      151       71  台湾省    98  151厘米   71千克    1.51
498  499   王勇  女  25      154       69  上海市    38  154厘米   69千克    1.54
499  500  王建平  男  18      157       47  陕西省    77  157厘米   47千克    1.57

[500 rows x 11 columns]

In [26]:
student['身高 (m)'] = student['身高 (cm)'] / 100
student

      学号   姓名 性别  年龄  身高 (cm)  体重 (kg)   籍贯  考试成绩 身高_带单位 体重_带单位  身高 (m)
0      1   邓娟  女  21      184       56  陕西省     7  184厘米   56千克    1.84
1      2   王畅  男  25      155       72  青海省    30  155厘米   72千克    1.55
2      3   储岩  女  23      166       56  辽宁省    28  166厘米   56千克    1.66
3      4   徐莉  女  24      150       57  山西省    98  150厘米   57千克    1.50
4      5   李波  男  20      175       55  海南省    14  175厘米   55千克    1.75
..   ...  ... ..  ..      ...      ...  ...   ...    ...    ...     ...
495  496  陈金凤  女  20      172       57  河北省    92  172厘米   57千克    1.72
496  497   马洋  男  19      173       56  上海市    48  173厘米   56千克    1.73
497  498   李峰  女  24      151       71  台湾省    98  151厘米   71千克    1.51
498  499   王勇  女  25      154       69  上海市    38  154厘米   69千克    1.54
499  500  王建平  男  18      157       47  陕西省    77  157厘米   47千克    1.57

[500 rows x 11 columns]

In [27]:
student['5级成绩'] = pd.cut(
    student['考试成绩'],
    bins=[-np.inf, 60, 70, 80, 90, np.inf],
    labels=['不及格', '及格', '中等', '良好', '优秀'],
    right=False   
)

#pd.cut(x, bins, right=True, labels=None,)
#x为要分箱的数据，bins是分箱的边界
#right=true默认(a, b]，right=false为[a,b]，labels是给区间起名字
#np.inf表示无穷

student

      学号   姓名 性别  年龄  身高 (cm)  体重 (kg)   籍贯  考试成绩 身高_带单位 体重_带单位  身高 (m) 5级成绩
0      1   邓娟  女  21      184       56  陕西省     7  184厘米   56千克    1.84  不及格
1      2   王畅  男  25      155       72  青海省    30  155厘米   72千克    1.55  不及格
2      3   储岩  女  23      166       56  辽宁省    28  166厘米   56千克    1.66  不及格
3      4   徐莉  女  24      150       57  山西省    98  150厘米   57千克    1.50   优秀
4      5   李波  男  20      175       55  海南省    14  175厘米   55千克    1.75  不及格
..   ...  ... ..  ..      ...      ...  ...   ...    ...    ...     ...  ...
495  496  陈金凤  女  20      172       57  河北省    92  172厘米   57千克    1.72   优秀
496  497   马洋  男  19      173       56  上海市    48  173厘米   56千克    1.73  不及格
497  498   李峰  女  24      151       71  台湾省    98  151厘米   71千克    1.51   优秀
498  499   王勇  女  25      154       69  上海市    38  154厘米   69千克    1.54  不及格
499  500  王建平  男  18      157       47  陕西省    77  157厘米   47千克    1.57   中等

[500 rows x 12 columns]

In [40]:
student[student['姓名'].str.startswith('李')]

#df[df['列名'].str.方法(参数)]

,学号,姓名,性别,年龄,身高 (cm),体重 (kg),籍贯,考试成绩,身高_带单位,体重_带单位,身高 (m),5级成绩
4,5,李波,男,20,175,55,海南省,14,175厘米,55千克,1.75,不及格
6,7,李兵,女,21,181,83,北京市,35,181厘米,83千克,1.81,不及格
9,10,李涛,男,24,164,78,新疆维吾尔自治区,84,164厘米,78千克,1.64,良好
63,64,李婷,男,22,190,48,云南省,1,190厘米,48千克,1.90,不及格
69,70,李淑兰,男,20,170,60,北京市,85,170厘米,60千克,1.70,良好
75,76,李欣,女,18,150,87,四川省,6,150厘米,87千克,1.50,不及格
88,89,李玉梅,女,18,175,84,香港特别行政区,81,175厘米,84千克,1.75,良好
104,105,李雪,女,21,158,71,河北省,25,158厘米,71千克,1.58,不及格
139,140,李秀荣,女,23,160,70,浙江省,2,160厘米,70千克,1.60,不及格
163,164,李娜,男,18,165,64,河北省,79,165厘米,64千克,1.65,中等
185,186,李斌,男,23,175,55,重庆市,39,175厘米,55千克,1.75,不及格
188,189,李勇,女,20,158,79,贵州省,97,158厘米,79千克,1.58,优秀
216,217,李利,男,20,182,61,陕西省,39,182厘米,61千克,1.82,不及格
230,231,李玉梅,女,21,150,78,辽宁省,45,150厘米,78千克,1.50,不及格
237,238,李秀华,女,25,158,84,重庆市,100,158厘米,84千克,1.58,优秀
238,239,李丹,女,18,169,53,山西省,40,169厘米,53千克,1.69,不及格
253,254,李玉梅,女,25,183,55,重庆市,53,183厘米,55千克,1.83,不及格
268,269,李龙,男,24,185,82,山西省,17,185厘米,82千克,1.85,不及格
271,272,李淑英,男,24,163,48,四川省,53,163厘米,48千克,1.63,不及格
287,288,李霞,男,25,178,87,重庆市,28,178厘米,87千克,1.78,不及格
323,324,李坤,女,24,176,47,重庆市,85,176厘米,47千克,1.76,良好
342,343,李秀兰,男,18,172,72,河南省,66,172厘米,72千克,1.72,及格
353,354,李柳,男,19,167,54,湖南省,53,167厘米,54千克,1.67,不及格
370,371,李浩,女,21,171,45,海南省,48,171厘米,45千克,1.71,不及格
386,387,李柳,男,19,179,86,吉林省,63,179厘米,86千克,1.79,及格
397,398,李丹,男,19,172,68,甘肃省,66,172厘米,68千克,1.72,及格
419,420,李淑兰,男,23,167,72,青海省,57,167厘米,72千克,1.67,不及格
435,436,李晨,女,25,173,49,浙江省,54,173厘米,49千克,1.73,不及格
445,446,李丽华,女,25,171,88,江西省,64,171厘米,88千克,1.71,及格
450,451,李雪,女,23,156,74,上海市,19,156厘米,74千克,1.56,不及格
451,452,李彬,男,22,178,55,上海市,62,178厘米,55千克,1.78,及格
460,461,李杨,男,20,181,47,山西省,38,181厘米,47千克,1.81,不及格
478,479,李秀兰,女,21,157,73,台湾省,0,157厘米,73千克,1.57,不及格
488,489,李想,女,20,154,63,安徽省,35,154厘米,63千克,1.54,不及格
497,498,李峰,女,24,151,71,台湾省,98,151厘米,71千克,1.51,优秀

In [29]:
student['身高_带单位'] = student['身高 (cm)'].astype(str)+ '厘米'
student['体重_带单位'] = student['体重 (kg)'].astype(str)+ '千克'
student

#.astype(str)是转换成字符串

      学号   姓名 性别  年龄  身高 (cm)  体重 (kg)   籍贯  考试成绩 身高_带单位 体重_带单位  身高 (m) 5级成绩
0      1   邓娟  女  21      184       56  陕西省     7  184厘米   56千克    1.84  不及格
1      2   王畅  男  25      155       72  青海省    30  155厘米   72千克    1.55  不及格
2      3   储岩  女  23      166       56  辽宁省    28  166厘米   56千克    1.66  不及格
3      4   徐莉  女  24      150       57  山西省    98  150厘米   57千克    1.50   优秀
4      5   李波  男  20      175       55  海南省    14  175厘米   55千克    1.75  不及格
..   ...  ... ..  ..      ...      ...  ...   ...    ...    ...     ...  ...
495  496  陈金凤  女  20      172       57  河北省    92  172厘米   57千克    1.72   优秀
496  497   马洋  男  19      173       56  上海市    48  173厘米   56千克    1.73  不及格
497  498   李峰  女  24      151       71  台湾省    98  151厘米   71千克    1.51   优秀
498  499   王勇  女  25      154       69  上海市    38  154厘米   69千克    1.54  不及格
499  500  王建平  男  18      157       47  陕西省    77  157厘米   47千克    1.57   中等

[500 rows x 12 columns]

In [30]:
student.groupby('性别').agg(
    平均成绩=('考试成绩', 'mean'),
    平均身高=('身高 (cm)', 'mean')
)

         平均成绩        平均身高
性别
女   51.586498  169.088608
男   49.441065  170.106464

In [31]:
student.groupby('籍贯').agg(
    学生数量=('姓名','count'),
    平均成绩=('考试成绩','mean'),
    平均体重=('体重 (kg)','mean')
)

          学生数量       平均成绩       平均体重
籍贯
上海市         23  42.826087  73.217391
云南省         16  37.562500  67.875000
内蒙古自治区      10  51.500000  70.400000
北京市         20  55.800000  67.350000
台湾省         16  54.437500  70.062500
吉林省         12  53.916667  68.666667
四川省         15  67.200000  63.000000
天津市         13  49.692308  65.230769
宁夏回族自治区     12  57.916667  69.333333
安徽省         17  47.117647  67.117647
山东省         16  54.437500  67.125000
山西省         21  39.190476  65.333333
广东省         11  44.727273  71.000000
广西壮族自治区     14  50.785714  65.000000
新疆维吾尔自治区    12  65.166667  66.916667
江苏省         14  54.214286  67.500000
江西省         20  47.800000  68.450000
河北省         22  41.454545  64.000000
河南省         15  38.800000  70.066667
浙江省          8  35.875000  65.125000
海南省         19  47.210526  65.526316
湖北省          8  43.375000  63.125000
湖南省         11  70.000000  64.454545
澳门特别行政区     12  53.916667  65.500000
甘肃省         14  53.928571  62.357143
福建省         12  60.000000  69.250000
西藏自治区        9  43.555556  66.222222
贵州省         14  52.928571  70.428571
辽宁省         20  45.400000  67.350000
重庆市         16  64.375000  64.000000
陕西省         18  55.000000  65.500000
青海省         13  44.000000  80.461538
香港特别行政区     14  51.071429  64.142857
黑龙江省        13  52.692308  74.000000

In [32]:
class1=pd.read_excel('教学信息.xlsx',sheet_name='班级')
class1

     班级编号  班级名称 班主任工号
0   CL001   班级1  T014
1   CL002   班级2  T023
2   CL003   班级3  T001
3   CL004   班级4  T013
4   CL005   班级5  T025
5   CL006   班级6  T002
6   CL007   班级7  T025
7   CL008   班级8  T028
8   CL009   班级9  T017
9   CL010  班级10  T021
10  CL011  班级11  T024
11  CL012  班级12  T013
12  CL013  班级13  T005
13  CL014  班级14  T007
14  CL015  班级15  T024
15  CL016  班级16  T028
16  CL017  班级17  T002
17  CL018  班级18  T027
18  CL019  班级19  T009
19  CL020  班级20  T003

In [33]:
class1_2 = class1.merge(teacher,
    left_on='班主任工号',  
    right_on='工号',
    how='left' 
)
class1_2['班主任工号'] = class1_2['姓名']
class1_2


#pd.merge() 的核心口诀：
#左表.merge(右表, left_on='左表键', right_on='右表键', how='连接方式')

     班级编号  班级名称 班主任工号    工号   姓名 性别  年龄  性别_数字
0   CL001   班级1   李玉兰  T014  李玉兰  女  46      0
1   CL002   班级2   董淑兰  T023  董淑兰  男  51      1
2   CL003   班级3   胡秀珍  T001  胡秀珍  男  29      1
3   CL004   班级4   祝秀华  T013  祝秀华  女  35      0
4   CL005   班级5   李冬梅  T025  李冬梅  女  43      0
5   CL006   班级6    赵想  T002   赵想  男  40      1
6   CL007   班级7   李冬梅  T025  李冬梅  女  43      0
7   CL008   班级8    何萍  T028   何萍  男  40      1
8   CL009   班级9   吴金凤  T017  吴金凤  男  28      1
9   CL010  班级10    余峰  T021   余峰  女  43      0
10  CL011  班级11    曹飞  T024   曹飞  女  47      0
11  CL012  班级12   祝秀华  T013  祝秀华  女  35      0
12  CL013  班级13   李红霞  T005  李红霞  女  30      0
13  CL014  班级14    罗畅  T007   罗畅  男  32      1
14  CL015  班级15    曹飞  T024   曹飞  女  47      0
15  CL016  班级16    何萍  T028   何萍  男  40      1
16  CL017  班级17    赵想  T002   赵想  男  40      1
17  CL018  班级18    徐宇  T027   徐宇  女  49      0
18  CL019  班级19    陶勇  T009   陶勇  女  55      0
19  CL020  班级20    吴洁  T003   吴洁  女  47      0

In [34]:
xk=pd.read_excel('教学信息.xlsx',sheet_name='选课')
xk

      选课编号   学号   班级编号  课程编号  教师编号
0        2    1  CL002  C002  T012
1        4    1  CL004  C004  T008
2        5    1  CL005  C005  T007
3        6    1  CL006  C006  T002
4        8    1  CL008  C008  T026
...    ...  ...    ...   ...   ...
5995  7000  500  CL016  C014  T016
5996  7500  500  CL017  C015  T008
5997  8500  500  CL019  C017  T002
5998  9000  500  CL020  C018  T008
5999  9500  500  CL001  C019  T013

[6000 rows x 5 columns]

In [41]:
xk["学生姓名"] = xk["学号"].map(student.set_index("学号")["姓名"])
xk["班级名称"] = xk["班级编号"].map(class1_2.set_index("班级编号")["班级名称"])
xk["教师姓名"] = xk["教师编号"].map(teacher.set_index("工号")["姓名"])
xk



#xk[新列名] = xk[键列名].map(映射表)
#映射表student.set_index("键列名")["值列名"]

      选课编号   学号   班级编号  课程编号  教师编号 学生姓名  班级名称 教师姓名
0        2    1  CL002  C002  T012   邓娟   班级2   江宇
1        4    1  CL004  C004  T008   邓娟   班级4   萧辉
2        5    1  CL005  C005  T007   邓娟   班级5   罗畅
3        6    1  CL006  C006  T002   邓娟   班级6   赵想
4        8    1  CL008  C008  T026   邓娟   班级8   吴亮
...    ...  ...    ...   ...   ...  ...   ...  ...
5995  7000  500  CL016  C014  T016  王建平  班级16   王飞
5996  7500  500  CL017  C015  T008  王建平  班级17   萧辉
5997  8500  500  CL019  C017  T002  王建平  班级19   赵想
5998  9000  500  CL020  C018  T008  王建平  班级20   萧辉
5999  9500  500  CL001  C019  T013  王建平   班级1  祝秀华

[6000 rows x 8 columns]